// Bakes the brush-script glyphs of sign catalog entries marked brush: true into
// src/brush-glyphs.mjs: 24×24 one-bit bitmaps of every Han character they use. Source font:
// LXGW WenKai TC (SIL Open Font License 1.1), https://github.com/lxgw/LxgwWenkaiTC; download
// LXGWWenKaiTC-Medium.ttf to cache/fonts/. The font itself is not committed.
//   node tools/brush-glyphs.mjs [cache/fonts/LXGWWenKaiTC-Medium.ttf]
import {readFile,writeFile} from 'node:fs/promises';
import opentype from 'opentype.js';
import catalog from '../src/sign-catalog.mjs';

const GRID=24,SS=6,THRESHOLD=.42;
const fontPath=process.argv[2]??'cache/fonts/LXGWWenKaiTC-Medium.ttf';
const bytes=await readFile(fontPath),font=opentype.parse(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));

const text=catalog.filter(e=>e.brush).flatMap(e=>e.sections??[e.text]).join('');
const chars=[...new Set(text.match(/\p{Script=Han}/gu))].sort((a,b)=>a.codePointAt(0)-b.codePointAt(0));

// One scale and offset for every glyph: the union of their ink boxes, centred, fills the grid
// less half a cell, so characters keep their relative sizes and sit mid-cell.
const glyphOf=ch=>{const glyph=font.charToGlyph(ch);if(!glyph||glyph.index===0)throw new Error(`Font has no glyph for "${ch}"`);return glyph;};
const union=chars.map(ch=>glyphOf(ch).getPath(0,0,1).getBoundingBox()).reduce((u,b)=>({x1:Math.min(u.x1,b.x1),y1:Math.min(u.y1,b.y1),x2:Math.max(u.x2,b.x2),y2:Math.max(u.y2,b.y2)}),{x1:Infinity,y1:Infinity,x2:-Infinity,y2:-Infinity});
const EM=(GRID-.5)*SS/Math.max(union.x2-union.x1,union.y2-union.y1);

// Contours of a glyph in supersampled pixels, curves flattened to short segments.
function contours(ch){
  const size=GRID*SS,glyph=glyphOf(ch);
  const path=glyph.getPath((size-(union.x1+union.x2)*EM)/2,(size-(union.y1+union.y2)*EM)/2,EM),out=[];let current=null,last=[0,0];
  const steps=10;
  for(const c of path.commands){
    if(c.type==='M'){current=[[c.x,c.y]];out.push(current);last=[c.x,c.y];}
    else if(c.type==='L'){current.push([c.x,c.y]);last=[c.x,c.y];}
    else if(c.type==='Q'){for(let i=1;i<=steps;i++){const t=i/steps,u=1-t;current.push([u*u*last[0]+2*u*t*c.x1+t*t*c.x,u*u*last[1]+2*u*t*c.y1+t*t*c.y]);}last=[c.x,c.y];}
    else if(c.type==='C'){for(let i=1;i<=steps;i++){const t=i/steps,u=1-t;current.push([u*u*u*last[0]+3*u*u*t*c.x1+3*u*t*t*c.x2+t*t*t*c.x,u*u*u*last[1]+3*u*u*t*c.y1+3*u*t*t*c.y2+t*t*t*c.y]);}last=[c.x,c.y];}
  }
  return out;
}

// Non-zero scanline fill, then the share of covered samples in each grid cell.
function bake(ch){
  const size=GRID*SS,cover=new Float32Array(GRID*GRID),edges=[];
  for(const ring of contours(ch))for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length];if(a[1]!==b[1])edges.push([a,b]);}
  for(let y=0;y<size;y++){
    const sy=y+.5,hits=[];
    for(const [a,b] of edges){const lo=Math.min(a[1],b[1]),hi=Math.max(a[1],b[1]);if(sy<lo||sy>=hi)continue;hits.push([a[0]+(sy-a[1])*(b[0]-a[0])/(b[1]-a[1]),b[1]>a[1]?1:-1]);}
    hits.sort((p,q)=>p[0]-q[0]);
    let winding=0;
    for(let i=0;i<hits.length-1;i++){
      winding+=hits[i][1];if(!winding)continue;
      for(let x=Math.max(0,Math.ceil(hits[i][0]-.5));x<Math.min(size,Math.ceil(hits[i+1][0]-.5));x++)cover[Math.floor(y/SS)*GRID+Math.floor(x/SS)]+=1/(SS*SS);
    }
  }
  return Array.from({length:GRID},(_,y)=>Array.from({length:GRID},(_,x)=>cover[y*GRID+x]>=THRESHOLD?1:0));
}

// Each row is six hex digits, most significant bit on the left.
const hex=rows=>rows.map(r=>parseInt(r.join(''),2).toString(16).padStart(6,'0')).join('');
const names=font.names.windows??font.names.macintosh??font.names,version=(names.version?.en??'unknown version').trim();
const lines=chars.map(ch=>` '${ch}':'${hex(bake(ch))}'`);
await writeFile('src/brush-glyphs.mjs',`// Generated by tools/brush-glyphs.mjs; do not edit. Brush-script bitmaps rasterised from
// LXGW WenKai TC Medium (${version}), © LXGW, licensed under the SIL Open Font License 1.1.
// ${GRID}×${GRID} one-bit glyphs: each row is six hex digits, most significant bit on the left.
export const BRUSH_GLYPH_SIZE=${GRID};
export const brushGlyphs={
${lines.join(',\n')}
};
`);
console.log(`${chars.length} glyphs from ${fontPath} (${version})`);
