// The sign catalog: everyday Japanese, Chinese, Korean and English trade words plus pictograms.
// Every text is a generic kind of shop, not a real business. {name} embeds an icon.
// Entry fields: id, kind (front | vertical | square | tower | rooftop), text or sections
// (towers; "small:" marks a small horizontal line), style (lightbox | neon | cutout),
// scheme (colour set in neon-signs.mjs), optional frame (plain | thick | bulbs | cap),
// business: the trade (or trades, for shared pictograms) it advertises, so one shop's
// fascia, projecting blade and pavement lightbox agree, and optional brush: true for
// Traditional Chinese in 24×24 brush script (src/brush-glyphs.mjs).
export default [
 {id:'drug',kind:'front',text:'DRUG 24',style:'lightbox',scheme:'green',business:'pharmacy'},
 {id:'cafe',kind:'front',text:'CAFE',style:'lightbox',scheme:'yellow',business:'cafe'},
 {id:'bakery',kind:'front',text:'BAKERY',style:'lightbox',scheme:'cream',business:'bakery'},
 {id:'bar',kind:'front',text:'BAR {cocktail}',style:'neon',scheme:'magenta',frame:'bulbs',business:'bar'},
 {id:'repair',kind:'front',text:'REPAIR',style:'lightbox',scheme:'cyan',business:'repair'},
 {id:'market',kind:'front',text:'MARKET',style:'lightbox',scheme:'red',frame:'thick',business:'market'},
 {id:'kafe-sora',kind:'front',text:'カフェ ソラ',style:'lightbox',scheme:'cream',business:'cafe'},
 {id:'ramen',kind:'front',text:'{bowl} ラーメン',style:'lightbox',scheme:'red',frame:'cap',business:'ramen'},
 {id:'karaoke',kind:'front',text:'カラオケ',style:'neon',scheme:'violet',frame:'bulbs',business:'karaoke'},
 {id:'video',kind:'front',text:'ビデオ',style:'lightbox',scheme:'cyan',business:'video'},
 {id:'game',kind:'front',text:'ゲーム',style:'neon',scheme:'green',business:'game'},
 {id:'snack-tsukiyo',kind:'front',text:'スナック 月夜',style:'neon',scheme:'magenta',business:'snack'},
 {id:'coffee',kind:'front',text:'COFFEE {coffee}',style:'lightbox',scheme:'cream',business:'cafe'},
 {id:'open24',kind:'front',text:'OPEN 24H',style:'neon',scheme:'red',frame:'thick',business:'convenience'},
 {id:'taxi',kind:'front',text:'TAXI',style:'lightbox',scheme:'yellow',business:'taxi'},
 {id:'hotel',kind:'front',text:'HOTEL',style:'neon',scheme:'violet',frame:'bulbs',business:'hotel'},
 {id:'dvd',kind:'front',text:'DVD {disc}',style:'lightbox',scheme:'cyan',business:'video'},
 {id:'wangba',kind:'front',text:'网吧',style:'neon',scheme:'cyan',business:'netcafe'},
 {id:'dianwan',kind:'front',text:'电玩 {gamepad}',style:'neon',scheme:'green',business:'arcade'},
 {id:'xiaoye',kind:'front',text:'宵夜',style:'lightbox',scheme:'red',frame:'cap',business:'xiaoye'},
 {id:'v-ramen',kind:'vertical',text:'ラーメン',style:'lightbox',scheme:'red',business:'ramen'},
 {id:'v-karaoke',kind:'vertical',text:'カラオケ',style:'neon',scheme:'violet',frame:'bulbs',business:'karaoke'},
 {id:'v-kusuri',kind:'vertical',text:'{cross}クスリ',style:'lightbox',scheme:'green',frame:'thick',business:'pharmacy'},
 {id:'v-video',kind:'vertical',text:'ビデオ',style:'neon',scheme:'cyan',business:'video'},
 {id:'v-game',kind:'vertical',text:'ゲーム',style:'neon',scheme:'green',business:'game'},
 {id:'v-hotel',kind:'vertical',text:'ホテル',style:'neon',scheme:'magenta',frame:'thick',business:'hotel'},
 {id:'v-snack',kind:'vertical',text:'スナック',style:'lightbox',scheme:'yellow',frame:'cap',business:'snack'},
 {id:'v-kafe',kind:'vertical',text:'カフェ',style:'lightbox',scheme:'cyan',business:'cafe'},
 {id:'v-sake',kind:'vertical',text:'酒',style:'lightbox',scheme:'cream',business:'izakaya'},
 {id:'v-hon',kind:'vertical',text:'本',style:'lightbox',scheme:'green',business:'books'},
 {id:'v-meshi',kind:'vertical',text:'めし',style:'neon',scheme:'red',business:'diner'},
 {id:'v-tsukiyo',kind:'vertical',text:'月夜',style:'neon',scheme:'yellow',business:'snack'},
 {id:'v-wangba',kind:'vertical',text:'网吧',style:'neon',scheme:'cyan',frame:'bulbs',business:'netcafe'},
 {id:'v-dianwan',kind:'vertical',text:'电玩',style:'lightbox',scheme:'violet',business:'arcade'},
 {id:'v-xiaoye',kind:'vertical',text:'宵夜',style:'lightbox',scheme:'yellow',business:'xiaoye'},
 {id:'v-hotel-en',kind:'vertical',text:'HOTEL',style:'neon',scheme:'red',frame:'bulbs',business:'hotel'},
 {id:'sq-bowl',kind:'square',text:'{bowl}',style:'lightbox',scheme:'red',business:['ramen','xiaoye','diner','jaulau']},
 {id:'sq-cross',kind:'square',text:'{cross}',style:'lightbox',scheme:'green',frame:'thick',business:['pharmacy','pharmacy-kr','yeukfong']},
 {id:'sq-disc',kind:'square',text:'{disc}',style:'neon',scheme:'violet',business:['video']},
 {id:'sq-cassette',kind:'square',text:'{cassette}',style:'neon',scheme:'cyan',business:['video']},
 {id:'sq-gamepad',kind:'square',text:'{gamepad}',style:'neon',scheme:'green',business:['game','arcade']},
 {id:'sq-cat',kind:'square',text:'{cat}',style:'neon',scheme:'violet',business:['snack']},
 {id:'sq-coffee',kind:'square',text:'{coffee}',style:'lightbox',scheme:'cream',business:['cafe','cafe-kr','bingshi','chachaan']},
 {id:'sq-cocktail',kind:'square',text:'{cocktail}',style:'neon',scheme:'magenta',frame:'bulbs',business:['bar']},
 {id:'sq-fish',kind:'square',text:'{fish}',style:'lightbox',scheme:'cyan',business:['sushi','hoimei']},
 {id:'sq-bolt',kind:'square',text:'{bolt}',style:'neon',scheme:'yellow',business:['repair','chefong']},
 {id:'sq-heart',kind:'square',text:'{heart}',style:'neon',scheme:'red',business:['karaoke','noraebang','snack','tongseui']},
 {id:'sq-sake',kind:'square',text:'酒',style:'lightbox',scheme:'cream',business:['izakaya','yakitori']},
 {id:'sq-24',kind:'square',text:'24',style:'lightbox',scheme:'red',frame:'thick',business:['convenience','pharmacy']},
 {id:'t-hotel',kind:'tower',sections:['ホテル','{bed}','small:HOTEL'],style:'lightbox',scheme:'red',frame:'thick',business:'hotel'},
 {id:'t-karaoke',kind:'tower',sections:['カラオケ','{heart}'],style:'neon',scheme:'magenta',frame:'bulbs',business:'karaoke'},
 {id:'t-ramen',kind:'tower',sections:['ラーメン','{bowl}'],style:'lightbox',scheme:'yellow',frame:'cap',business:'ramen'},
 {id:'t-sushi',kind:'tower',sections:['寿司','{fish}'],style:'lightbox',scheme:'cream',frame:'thick',business:'sushi'},
 {id:'t-cinema',kind:'tower',sections:['CINEMA'],style:'neon',scheme:'yellow',frame:'bulbs',business:'cinema'},
 {id:'t-wangba',kind:'tower',sections:['网吧','small:NET 24H'],style:'neon',scheme:'cyan',frame:'thick',business:'netcafe'},
 {id:'t-snack',kind:'tower',sections:['スナック','月夜'],style:'lightbox',scheme:'violet',frame:'cap',business:'snack'},
 {id:'t-bar',kind:'tower',sections:['BAR','{cocktail}'],style:'neon',scheme:'magenta',frame:'bulbs',business:'bar'},
 {id:'t-drug',kind:'tower',sections:['{cross}','クスリ','small:DRUG'],style:'lightbox',scheme:'cyan',frame:'cap',business:'pharmacy'},
 {id:'t-game',kind:'tower',sections:['ゲーム','{gamepad}'],style:'neon',scheme:'green',frame:'bulbs',business:'game'},
 {id:'r-supermarket',kind:'rooftop',text:'SUPERMARKET',style:'cutout',scheme:'red',business:'market'},
 {id:'r-cinema',kind:'rooftop',text:'CINEMA',style:'cutout',scheme:'yellow',business:'cinema'},
 {id:'r-karaoke',kind:'rooftop',text:'KARAOKE',style:'cutout',scheme:'cyan',business:'karaoke'},
 {id:'r-hotel',kind:'rooftop',text:'ホテル',style:'cutout',scheme:'violet',business:'hotel'},
 {id:'r-dvd',kind:'rooftop',text:'DVD {disc}',style:'cutout',scheme:'green',business:'video'},
 {id:'r-dianwan',kind:'rooftop',text:'电玩 {gamepad}',style:'cutout',scheme:'magenta',business:'arcade'},
 {id:'k-noraebang',kind:'front',text:'노래방',style:'neon',scheme:'violet',frame:'bulbs',business:'noraebang'},
 {id:'k-chicken',kind:'front',text:'치킨 {drumstick}',style:'lightbox',scheme:'yellow',business:'chicken'},
 {id:'k-bunsik',kind:'front',text:'분식',style:'lightbox',scheme:'red',frame:'cap',business:'bunsik'},
 {id:'k-hof',kind:'front',text:'호프 {beer}',style:'neon',scheme:'yellow',business:'hof'},
 {id:'k-coffee',kind:'front',text:'커피',style:'lightbox',scheme:'cream',business:'cafe-kr'},
 {id:'k-pharmacy',kind:'front',text:'약국',style:'lightbox',scheme:'green',frame:'thick',business:'pharmacy-kr'},
 {id:'yakitori',kind:'front',text:'ヤキトリ',style:'lightbox',scheme:'red',frame:'cap',business:'yakitori'},
 {id:'beer',kind:'front',text:'ビール {beer}',style:'neon',scheme:'yellow',business:'beer'},
 {id:'bingshi',kind:'front',text:'冰室',style:'lightbox',scheme:'cyan',frame:'thick',business:'bingshi'},
 {id:'laundry',kind:'front',text:'LAUNDRY',style:'lightbox',scheme:'cyan',business:'laundry'},
 {id:'books',kind:'front',text:'BOOKS',style:'lightbox',scheme:'cream',frame:'thick',business:'books'},
 {id:'arcade',kind:'front',text:'ARCADE {gamepad}',style:'neon',scheme:'green',frame:'bulbs',business:'arcade'},
 {id:'sushi',kind:'front',text:'SUSHI {fish}',style:'lightbox',scheme:'cream',business:'sushi'},
 {id:'photo',kind:'front',text:'PHOTO',style:'lightbox',scheme:'yellow',business:'photo'},
 {id:'v-noraebang',kind:'vertical',text:'노래방',style:'neon',scheme:'magenta',frame:'bulbs',business:'noraebang'},
 {id:'v-chicken',kind:'vertical',text:'치킨',style:'lightbox',scheme:'red',business:'chicken'},
 {id:'v-bunsik',kind:'vertical',text:'분식',style:'lightbox',scheme:'yellow',business:'bunsik'},
 {id:'v-hof',kind:'vertical',text:'호프',style:'neon',scheme:'cyan',business:'hof'},
 {id:'v-pharmacy',kind:'vertical',text:'약국',style:'lightbox',scheme:'green',frame:'thick',business:'pharmacy-kr'},
 {id:'v-yakitori',kind:'vertical',text:'ヤキトリ',style:'lightbox',scheme:'cream',business:'yakitori'},
 {id:'v-cake',kind:'vertical',text:'ケーキ',style:'lightbox',scheme:'magenta',business:'bakery'},
 {id:'v-bingshi',kind:'vertical',text:'冰室',style:'neon',scheme:'cyan',business:'bingshi'},
 {id:'v-cha',kind:'vertical',text:'茶',style:'lightbox',scheme:'green',business:'tea'},
 {id:'sq-beer',kind:'square',text:'{beer}',style:'neon',scheme:'yellow',business:['beer','hof','bar']},
 {id:'sq-drumstick',kind:'square',text:'{drumstick}',style:'lightbox',scheme:'red',business:['chicken','yakitori','siulaap']},
 {id:'sq-mian',kind:'square',text:'面',style:'lightbox',scheme:'red',frame:'thick',business:['xiaoye','ramen']},
 {id:'t-noraebang',kind:'tower',sections:['노래방','{heart}'],style:'neon',scheme:'cyan',frame:'bulbs',business:'noraebang'},
 {id:'t-chicken',kind:'tower',sections:['치킨','{drumstick}','small:CHICKEN'],style:'lightbox',scheme:'red',frame:'cap',business:'chicken'},
 {id:'t-hof',kind:'tower',sections:['호프','{beer}'],style:'neon',scheme:'yellow',frame:'thick',business:'hof'},
 {id:'t-yakitori',kind:'tower',sections:['ヤキトリ','{drumstick}'],style:'lightbox',scheme:'yellow',frame:'cap',business:'yakitori'},
 {id:'t-bingshi',kind:'tower',sections:['冰室','small:CAFE'],style:'lightbox',scheme:'cyan',frame:'cap',business:'bingshi'},
 {id:'r-noraebang',kind:'rooftop',text:'노래방',style:'cutout',scheme:'magenta',business:'noraebang'},
 {id:'chachaan',kind:'front',text:'茶餐廳 {coffee}',style:'lightbox',scheme:'cream',frame:'thick',brush:true,business:'chachaan'},
 {id:'yeukfong',kind:'front',text:'{cross} 藥房',style:'lightbox',scheme:'green',brush:true,business:'yeukfong'},
 {id:'siulaap',kind:'front',text:'燒臘 {drumstick}',style:'lightbox',scheme:'red',frame:'cap',brush:true,business:'siulaap'},
 {id:'gamhong',kind:'front',text:'金行珠寶',style:'neon',scheme:'yellow',frame:'bulbs',brush:true,business:'gamhong'},
 {id:'hoimei',kind:'front',text:'海味乾貨',style:'lightbox',scheme:'red',brush:true,business:'hoimei'},
 {id:'chefong',kind:'front',text:'汽車維修',style:'lightbox',scheme:'cyan',frame:'thick',brush:true,business:'chefong'},
 {id:'tongseui',kind:'front',text:'糖水甜品',style:'neon',scheme:'magenta',brush:true,business:'tongseui'},
 {id:'v-jaulau',kind:'vertical',text:'酒樓',style:'neon',scheme:'magenta',frame:'bulbs',brush:true,business:'jaulau'},
 {id:'v-chachaan',kind:'vertical',text:'茶餐廳',style:'lightbox',scheme:'cream',frame:'thick',brush:true,business:'chachaan'},
 {id:'v-yeukfong',kind:'vertical',text:'藥房',style:'lightbox',scheme:'green',frame:'thick',brush:true,business:'yeukfong'},
 {id:'v-siulaap',kind:'vertical',text:'燒臘',style:'lightbox',scheme:'red',brush:true,business:'siulaap'},
 {id:'t-jaulau',kind:'tower',sections:['酒樓','{bowl}'],style:'neon',scheme:'red',frame:'bulbs',brush:true,business:'jaulau'}
];
