// The sign catalog: everyday Japanese, Chinese, Korean and English trade words plus pictograms.
// Every text is a generic kind of shop, not a real business. {name} embeds an icon.
// Entry fields: id, kind (front | vertical | square | tower | rooftop), text or sections
// (towers; "small:" marks a small horizontal line), style (lightbox | neon | cutout),
// scheme (colour set in neon-signs.mjs), optional frame (plain | thick | bulbs | cap).
export default [
 {id:'drug',kind:'front',text:'DRUG 24',style:'lightbox',scheme:'green'},
 {id:'cafe',kind:'front',text:'CAFE',style:'lightbox',scheme:'yellow'},
 {id:'bakery',kind:'front',text:'BAKERY',style:'lightbox',scheme:'cream'},
 {id:'bar',kind:'front',text:'BAR {cocktail}',style:'neon',scheme:'magenta',frame:'bulbs'},
 {id:'repair',kind:'front',text:'REPAIR',style:'lightbox',scheme:'cyan'},
 {id:'market',kind:'front',text:'MARKET',style:'lightbox',scheme:'red',frame:'thick'},
 {id:'kafe-sora',kind:'front',text:'カフェ ソラ',style:'lightbox',scheme:'cream'},
 {id:'ramen',kind:'front',text:'{bowl} ラーメン',style:'lightbox',scheme:'red',frame:'cap'},
 {id:'karaoke',kind:'front',text:'カラオケ',style:'neon',scheme:'violet',frame:'bulbs'},
 {id:'video',kind:'front',text:'ビデオ',style:'lightbox',scheme:'cyan'},
 {id:'game',kind:'front',text:'ゲーム',style:'neon',scheme:'green'},
 {id:'snack-tsukiyo',kind:'front',text:'スナック 月夜',style:'neon',scheme:'magenta'},
 {id:'coffee',kind:'front',text:'COFFEE {coffee}',style:'lightbox',scheme:'cream'},
 {id:'open24',kind:'front',text:'OPEN 24H',style:'neon',scheme:'red',frame:'thick'},
 {id:'taxi',kind:'front',text:'TAXI',style:'lightbox',scheme:'yellow'},
 {id:'hotel',kind:'front',text:'HOTEL',style:'neon',scheme:'violet',frame:'bulbs'},
 {id:'dvd',kind:'front',text:'DVD {disc}',style:'lightbox',scheme:'cyan'},
 {id:'wangba',kind:'front',text:'网吧',style:'neon',scheme:'cyan'},
 {id:'dianwan',kind:'front',text:'电玩 {gamepad}',style:'neon',scheme:'green'},
 {id:'xiaoye',kind:'front',text:'宵夜',style:'lightbox',scheme:'red',frame:'cap'},
 {id:'v-ramen',kind:'vertical',text:'ラーメン',style:'lightbox',scheme:'red'},
 {id:'v-karaoke',kind:'vertical',text:'カラオケ',style:'neon',scheme:'violet',frame:'bulbs'},
 {id:'v-kusuri',kind:'vertical',text:'{cross}クスリ',style:'lightbox',scheme:'green',frame:'thick'},
 {id:'v-video',kind:'vertical',text:'ビデオ',style:'neon',scheme:'cyan'},
 {id:'v-game',kind:'vertical',text:'ゲーム',style:'neon',scheme:'green'},
 {id:'v-hotel',kind:'vertical',text:'ホテル',style:'neon',scheme:'magenta',frame:'thick'},
 {id:'v-snack',kind:'vertical',text:'スナック',style:'lightbox',scheme:'yellow',frame:'cap'},
 {id:'v-kafe',kind:'vertical',text:'カフェ',style:'lightbox',scheme:'cyan'},
 {id:'v-sake',kind:'vertical',text:'酒',style:'lightbox',scheme:'cream'},
 {id:'v-hon',kind:'vertical',text:'本',style:'lightbox',scheme:'green'},
 {id:'v-meshi',kind:'vertical',text:'めし',style:'neon',scheme:'red'},
 {id:'v-tsukiyo',kind:'vertical',text:'月夜',style:'neon',scheme:'yellow'},
 {id:'v-wangba',kind:'vertical',text:'网吧',style:'neon',scheme:'cyan',frame:'bulbs'},
 {id:'v-dianwan',kind:'vertical',text:'电玩',style:'lightbox',scheme:'violet'},
 {id:'v-xiaoye',kind:'vertical',text:'宵夜',style:'lightbox',scheme:'yellow'},
 {id:'v-hotel-en',kind:'vertical',text:'HOTEL',style:'neon',scheme:'red',frame:'bulbs'},
 {id:'sq-bowl',kind:'square',text:'{bowl}',style:'lightbox',scheme:'red'},
 {id:'sq-cross',kind:'square',text:'{cross}',style:'lightbox',scheme:'green',frame:'thick'},
 {id:'sq-disc',kind:'square',text:'{disc}',style:'neon',scheme:'violet'},
 {id:'sq-cassette',kind:'square',text:'{cassette}',style:'neon',scheme:'cyan'},
 {id:'sq-gamepad',kind:'square',text:'{gamepad}',style:'neon',scheme:'green'},
 {id:'sq-cat',kind:'square',text:'{cat}',style:'neon',scheme:'violet'},
 {id:'sq-coffee',kind:'square',text:'{coffee}',style:'lightbox',scheme:'cream'},
 {id:'sq-cocktail',kind:'square',text:'{cocktail}',style:'neon',scheme:'magenta',frame:'bulbs'},
 {id:'sq-fish',kind:'square',text:'{fish}',style:'lightbox',scheme:'cyan'},
 {id:'sq-bolt',kind:'square',text:'{bolt}',style:'neon',scheme:'yellow'},
 {id:'sq-heart',kind:'square',text:'{heart}',style:'neon',scheme:'red'},
 {id:'sq-sake',kind:'square',text:'酒',style:'lightbox',scheme:'cream'},
 {id:'sq-24',kind:'square',text:'24',style:'lightbox',scheme:'red',frame:'thick'},
 {id:'t-hotel',kind:'tower',sections:['ホテル','{bed}','small:HOTEL'],style:'lightbox',scheme:'red',frame:'thick'},
 {id:'t-karaoke',kind:'tower',sections:['カラオケ','{heart}'],style:'neon',scheme:'magenta',frame:'bulbs'},
 {id:'t-ramen',kind:'tower',sections:['ラーメン','{bowl}'],style:'lightbox',scheme:'yellow',frame:'cap'},
 {id:'t-sushi',kind:'tower',sections:['寿司','{fish}'],style:'lightbox',scheme:'cream',frame:'thick'},
 {id:'t-cinema',kind:'tower',sections:['CINEMA'],style:'neon',scheme:'yellow',frame:'bulbs'},
 {id:'t-wangba',kind:'tower',sections:['网吧','small:NET 24H'],style:'neon',scheme:'cyan',frame:'thick'},
 {id:'t-snack',kind:'tower',sections:['スナック','月夜'],style:'lightbox',scheme:'violet',frame:'cap'},
 {id:'t-bar',kind:'tower',sections:['BAR','{cocktail}'],style:'neon',scheme:'magenta',frame:'bulbs'},
 {id:'t-drug',kind:'tower',sections:['{cross}','クスリ','small:DRUG'],style:'lightbox',scheme:'cyan',frame:'cap'},
 {id:'t-game',kind:'tower',sections:['ゲーム','{gamepad}'],style:'neon',scheme:'green',frame:'bulbs'},
 {id:'r-supermarket',kind:'rooftop',text:'SUPERMARKET',style:'cutout',scheme:'red'},
 {id:'r-cinema',kind:'rooftop',text:'CINEMA',style:'cutout',scheme:'yellow'},
 {id:'r-karaoke',kind:'rooftop',text:'KARAOKE',style:'cutout',scheme:'cyan'},
 {id:'r-hotel',kind:'rooftop',text:'ホテル',style:'cutout',scheme:'violet'},
 {id:'r-dvd',kind:'rooftop',text:'DVD {disc}',style:'cutout',scheme:'green'},
 {id:'r-dianwan',kind:'rooftop',text:'电玩 {gamepad}',style:'cutout',scheme:'magenta'},
 {id:'k-noraebang',kind:'front',text:'노래방',style:'neon',scheme:'violet',frame:'bulbs'},
 {id:'k-chicken',kind:'front',text:'치킨 {drumstick}',style:'lightbox',scheme:'yellow'},
 {id:'k-bunsik',kind:'front',text:'분식',style:'lightbox',scheme:'red',frame:'cap'},
 {id:'k-hof',kind:'front',text:'호프 {beer}',style:'neon',scheme:'yellow'},
 {id:'k-coffee',kind:'front',text:'커피',style:'lightbox',scheme:'cream'},
 {id:'k-pharmacy',kind:'front',text:'약국',style:'lightbox',scheme:'green',frame:'thick'},
 {id:'yakitori',kind:'front',text:'ヤキトリ',style:'lightbox',scheme:'red',frame:'cap'},
 {id:'beer',kind:'front',text:'ビール {beer}',style:'neon',scheme:'yellow'},
 {id:'bingshi',kind:'front',text:'冰室',style:'lightbox',scheme:'cyan',frame:'thick'},
 {id:'laundry',kind:'front',text:'LAUNDRY',style:'lightbox',scheme:'cyan'},
 {id:'books',kind:'front',text:'BOOKS',style:'lightbox',scheme:'cream',frame:'thick'},
 {id:'arcade',kind:'front',text:'ARCADE {gamepad}',style:'neon',scheme:'green',frame:'bulbs'},
 {id:'sushi',kind:'front',text:'SUSHI {fish}',style:'lightbox',scheme:'cream'},
 {id:'photo',kind:'front',text:'PHOTO',style:'lightbox',scheme:'yellow'},
 {id:'v-noraebang',kind:'vertical',text:'노래방',style:'neon',scheme:'magenta',frame:'bulbs'},
 {id:'v-chicken',kind:'vertical',text:'치킨',style:'lightbox',scheme:'red'},
 {id:'v-bunsik',kind:'vertical',text:'분식',style:'lightbox',scheme:'yellow'},
 {id:'v-hof',kind:'vertical',text:'호프',style:'neon',scheme:'cyan'},
 {id:'v-pharmacy',kind:'vertical',text:'약국',style:'lightbox',scheme:'green',frame:'thick'},
 {id:'v-yakitori',kind:'vertical',text:'ヤキトリ',style:'lightbox',scheme:'cream'},
 {id:'v-cake',kind:'vertical',text:'ケーキ',style:'lightbox',scheme:'magenta'},
 {id:'v-bingshi',kind:'vertical',text:'冰室',style:'neon',scheme:'cyan'},
 {id:'v-cha',kind:'vertical',text:'茶',style:'lightbox',scheme:'green'},
 {id:'sq-beer',kind:'square',text:'{beer}',style:'neon',scheme:'yellow'},
 {id:'sq-drumstick',kind:'square',text:'{drumstick}',style:'lightbox',scheme:'red'},
 {id:'sq-mian',kind:'square',text:'面',style:'lightbox',scheme:'red',frame:'thick'},
 {id:'t-noraebang',kind:'tower',sections:['노래방','{heart}'],style:'neon',scheme:'cyan',frame:'bulbs'},
 {id:'t-chicken',kind:'tower',sections:['치킨','{drumstick}','small:CHICKEN'],style:'lightbox',scheme:'red',frame:'cap'},
 {id:'t-hof',kind:'tower',sections:['호프','{beer}'],style:'neon',scheme:'yellow',frame:'thick'},
 {id:'t-yakitori',kind:'tower',sections:['ヤキトリ','{drumstick}'],style:'lightbox',scheme:'yellow',frame:'cap'},
 {id:'t-bingshi',kind:'tower',sections:['冰室','small:CAFE'],style:'lightbox',scheme:'cyan',frame:'cap'},
 {id:'r-noraebang',kind:'rooftop',text:'노래방',style:'cutout',scheme:'magenta'}
];
